### ISSUE TITLE
Err: could not send report:

### ISSUE THREAD

**Issue by s33dunda** [thomasvandoren/puppet-zabbix#1]
I've installed and configured according to the manual but cant seem to get it to run. The err out put is: 
err: Could not send report: Error 400 on SERVER: Could not autoload zabbix: no such file to load -- open4

I am still a noob to the sys admin world. so bear with me. I have tried cp the open4 gems to the puppet gems dir as well as keeping it in the system gems dir. Not sure what else to look for.

I should mention this is running puppet 2.7.19 (Puppet Enterprise 2.6.1) on ubuntu12.04 lts server

**Comment by thomasvandoren** [comment]
After installing gems, I usually have to bounce the puppetmaster. I haven't tried this with PE, but on the community version it has worked to install the gems on the system gem path with

``` bash
sudo gem install open4
sudo service puppetmaster restart
```

**Comment by s33dunda** [comment]
Thanks for the quick response.
I restarted all of the services and tried again. fail. 
Any other ideas?
I'm going to try looking through the strace for more info.

**Comment by s33dunda** [comment]
Ok I found the issue the there was another ruby directory that puppet was reading from that i was not aware of. Good to go. Thanks again
