### ISSUE TITLE
Flapping 'Puppet has not run recently'

### ISSUE THREAD

**Issue by lennardk** [thomasvandoren/puppet-zabbix#2]
In some cases, the trigger 'Puppet has not run recently' will be flapping.
The cause of this is the item definition for puppet.run.time_since_last (last(system.localtime) - last(puppet.run.timestamp)) going negative in those cases, due to the last system.localtime being submitted before the last puppet.run.timestamp.
Replacing last(system.localtime) with now(x), where x is some valid item such as puppet.run.timestamp (but its value will be ignored), will fix the issue, assuming all clocks are synced.

**Comment by thomasvandoren** [comment]
Archiving this repo and closing all open issues.
