### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by johntest035** [thomasvandoren/puppet-zabbix#3]
Sequence of steps (on puppet master)
sudo gem install open4
puppet module install thomasvandoren-zabbix
## Here is zabbix.yaml

zabbix_host: 'zabbix1'
zabbix_port: '10051'
zabbix_sender: '/usr/bin/zabbix_sender'

"zabbix1" resolves to the IP address of zabbix server just fine.

Here is puppet.conf
[main]
    logdir = /var/log/puppet
    rundir = /var/run/puppet
    ssldir = $vardir/ssl
    privatekeydir = $ssldir/private_keys { group = service }
    hostprivkey = $privatekeydir/$certname.pem { mode = 640 }
    autosign       = $confdir/autosign.conf { mode = 664 }
    show_diff     = false
    hiera_config = $confdir/hiera.yaml
    report            = true
    pluginsync        = true

[agent]
    classfile = $vardir/classes.txt
    localconfig = $vardir/localconfig
    default_schedules = false
    masterport        = 8140
    environment       = production
    certname          = foreman1.fjos.local
    server            = foreman1.fjos.local
    listen            = false
    splay             = false
    splaylimit        = 1800
    runinterval       = 1800
    noop              = false
    configtimeout     = 120
    usecacheonfailure = true

[master]
    autosign       = $confdir/autosign.conf { mode = 664 }
    reports        = log,foreman,zabbix1   # no spaces after commas
    external_nodes = /etc/puppet/node.rb
    node_terminus  = exec
    ca             = true
    ssldir         = /var/lib/puppet/ssl
    certname       = foreman1.domain1.local
    strict_variables = false
    environmentpath  = /etc/puppet/environments
    basemodulepath   = /etc/puppet/environments/common:/etc/puppet/modules:/usr/share/puppet/modules

Here is the error
Feb 17 15:43:43 foreman1 puppet-master[1397]: Failed to send puppet data to zabbix (zabbix1:10051) for ubuntu-system1

**Comment by thomasvandoren** [comment]
Archiving this repo and closing all open issues.
